/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package UI;

import Connection_MySQL_UsuarioDAO.UsuarioDAO;
import Connection_Usuarios.Usuario;
import static javax.swing.JOptionPane.showMessageDialog;

/**
 *
 * @author 23.01425-3
 */
public class TelaAdministradorAtuUsu extends javax.swing.JFrame {

    /**
     * Creates new form TelaAdministradorCadUsu
     */
    public TelaAdministradorAtuUsu() {
        initComponents();
        setLocationRelativeTo(null);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        novonomeTextField = new javax.swing.JTextField();
        novoraTextField = new javax.swing.JTextField();
        novoemailTextField = new javax.swing.JTextField();
        novasenhaPasswordField = new javax.swing.JPasswordField();
        atualizarButton = new javax.swing.JButton();
        raBuscaTextField = new javax.swing.JTextField();
        DoskaLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cadastrar Usuários");
        setBackground(new java.awt.Color(255, 255, 255));

        novonomeTextField.setBorder(javax.swing.BorderFactory.createTitledBorder("novo nome do usuário:"));
        novonomeTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                novonomeTextFieldActionPerformed(evt);
            }
        });

        novoraTextField.setBorder(javax.swing.BorderFactory.createTitledBorder("novo ra do usuário (login):"));
        novoraTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                novoraTextFieldActionPerformed(evt);
            }
        });

        novoemailTextField.setBorder(javax.swing.BorderFactory.createTitledBorder("novo e-mail do usuário:"));
        novoemailTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                novoemailTextFieldActionPerformed(evt);
            }
        });

        novasenhaPasswordField.setBorder(javax.swing.BorderFactory.createTitledBorder("nova senha:"));
        novasenhaPasswordField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                novasenhaPasswordFieldActionPerformed(evt);
            }
        });

        atualizarButton.setText("atualizar");
        atualizarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                atualizarButtonActionPerformed(evt);
            }
        });

        raBuscaTextField.setBorder(javax.swing.BorderFactory.createTitledBorder("ra do usuário a ser atualizado:"));
        raBuscaTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                raBuscaTextFieldActionPerformed(evt);
            }
        });

        DoskaLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/pixil-frame-0__1__Easy-Resize.com-removebg-preview.png"))); // NOI18N
        DoskaLabel.setText("jLabel1");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(433, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(novasenhaPasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addComponent(atualizarButton, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(494, 494, 494))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(novoraTextField)
                                .addComponent(novonomeTextField)
                                .addComponent(novoemailTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 238, Short.MAX_VALUE)
                                .addComponent(raBuscaTextField))
                            .addGap(429, 429, 429))
                        .addComponent(DoskaLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(103, 103, 103)
                .addComponent(raBuscaTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(novonomeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(novoraTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(13, 13, 13)
                .addComponent(novoemailTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addComponent(novasenhaPasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(atualizarButton, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                .addComponent(DoskaLabel))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void novonomeTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_novonomeTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_novonomeTextFieldActionPerformed

    private void novoraTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_novoraTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_novoraTextFieldActionPerformed

    private void novoemailTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_novoemailTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_novoemailTextFieldActionPerformed

    private void novasenhaPasswordFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_novasenhaPasswordFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_novasenhaPasswordFieldActionPerformed

    private void raBuscaTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_raBuscaTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_raBuscaTextFieldActionPerformed

    private void atualizarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_atualizarButtonActionPerformed
        try{
            String raBusca = raBuscaTextField.getText();
            String novoNome = novonomeTextField.getText();
            String novoRa = novoraTextField.getText();
            String novoEmail = novoemailTextField.getText();
            String novaSenha = new String(novasenhaPasswordField.getPassword());
            var u = new Usuario(novoRa, novoNome, novoEmail, novaSenha, raBusca);
            var dao = new UsuarioDAO();
            dao.atualizar(u);


        }
        catch(Exception e){
             showMessageDialog(null, "Falha técnica. Tente novamente mais tarde");
             e.printStackTrace();
        }
    }//GEN-LAST:event_atualizarButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaAdministradorAtuUsu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaAdministradorAtuUsu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaAdministradorAtuUsu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaAdministradorAtuUsu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaAdministradorAtuUsu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel DoskaLabel;
    private javax.swing.JButton atualizarButton;
    private javax.swing.JPasswordField novasenhaPasswordField;
    private javax.swing.JTextField novoemailTextField;
    private javax.swing.JTextField novonomeTextField;
    private javax.swing.JTextField novoraTextField;
    private javax.swing.JTextField raBuscaTextField;
    // End of variables declaration//GEN-END:variables
}
