/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package UI;

/**
 *
 * @author 23.01425-3
 */
public class TelaAdministradorCadastros extends javax.swing.JFrame {

    /**
     * Creates new form telaAdministradorInicial
     */
    public TelaAdministradorCadastros() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        voltarButton = new javax.swing.JButton();
        cadastrarUsuarioButton = new javax.swing.JButton();
        atualizarUsuarioButton = new javax.swing.JButton();
        excluirUsuarioButton1 = new javax.swing.JButton();
        telaLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        voltarButton.setBackground(new java.awt.Color(0, 23, 103));
        voltarButton.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        voltarButton.setForeground(new java.awt.Color(255, 255, 255));
        voltarButton.setText("voltar");
        voltarButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        voltarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                voltarButtonActionPerformed(evt);
            }
        });
        getContentPane().add(voltarButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 590, 110, 40));

        cadastrarUsuarioButton.setBackground(new java.awt.Color(0, 23, 103));
        cadastrarUsuarioButton.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        cadastrarUsuarioButton.setForeground(new java.awt.Color(255, 255, 255));
        cadastrarUsuarioButton.setText("cadastrar usuário");
        cadastrarUsuarioButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cadastrarUsuarioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadastrarUsuarioButtonActionPerformed(evt);
            }
        });
        getContentPane().add(cadastrarUsuarioButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 270, 210, 60));

        atualizarUsuarioButton.setBackground(new java.awt.Color(0, 23, 103));
        atualizarUsuarioButton.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        atualizarUsuarioButton.setForeground(new java.awt.Color(255, 255, 255));
        atualizarUsuarioButton.setText("atualizar usuário");
        atualizarUsuarioButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        atualizarUsuarioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                atualizarUsuarioButtonActionPerformed(evt);
            }
        });
        getContentPane().add(atualizarUsuarioButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 370, 210, 60));

        excluirUsuarioButton1.setBackground(new java.awt.Color(0, 23, 103));
        excluirUsuarioButton1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        excluirUsuarioButton1.setForeground(new java.awt.Color(255, 255, 255));
        excluirUsuarioButton1.setText("excluir usuário");
        excluirUsuarioButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        excluirUsuarioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                excluirUsuarioButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(excluirUsuarioButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 470, 210, 60));

        telaLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/telaInicialAdministradorImage.png"))); // NOI18N
        telaLabel.addContainerListener(new java.awt.event.ContainerAdapter() {
            public void componentAdded(java.awt.event.ContainerEvent evt) {
                telaLabelComponentAdded(evt);
            }
        });
        getContentPane().add(telaLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void voltarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_voltarButtonActionPerformed
        var telaAdminInicial = new TelaAdministradorInicial();
        telaAdminInicial.setVisible(true);
        dispose();
    }//GEN-LAST:event_voltarButtonActionPerformed

    private void cadastrarUsuarioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadastrarUsuarioButtonActionPerformed
        var telaAdministradorCadUsu = new TelaAdministradorCadUsu();
        telaAdministradorCadUsu.setVisible(true);
    }//GEN-LAST:event_cadastrarUsuarioButtonActionPerformed

    private void atualizarUsuarioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_atualizarUsuarioButtonActionPerformed
        var telaAdminAtuUsu = new TelaAdministradorAtuUsu();
        telaAdminAtuUsu.setVisible(true);
    }//GEN-LAST:event_atualizarUsuarioButtonActionPerformed

    private void telaLabelComponentAdded(java.awt.event.ContainerEvent evt) {//GEN-FIRST:event_telaLabelComponentAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_telaLabelComponentAdded

    private void excluirUsuarioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_excluirUsuarioButton1ActionPerformed
        var telaExcUsu = new TelaAdministradorExcUsu();
        telaExcUsu.setVisible(true);
    }//GEN-LAST:event_excluirUsuarioButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaAdministradorCadastros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaAdministradorCadastros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaAdministradorCadastros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaAdministradorCadastros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaAdministradorCadastros().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton atualizarUsuarioButton;
    private javax.swing.JButton cadastrarUsuarioButton;
    private javax.swing.JButton excluirUsuarioButton1;
    private javax.swing.JLabel telaLabel;
    private javax.swing.JButton voltarButton;
    // End of variables declaration//GEN-END:variables
}
