/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package UI;

import Connection_MySQL_RespostasDAO.RespostasDAO;
import Connection_MySQL_UsuarioDAO.UsuarioDAO;
import Connection_Respostas.Respostas;
import Connection_Usuarios.Usuario;
import static javax.swing.JOptionPane.showMessageDialog;

/**
 *
 * @author 23.01425-3
 */
public class TelaCadastro extends javax.swing.JFrame {

    /**
     * Creates new form TelaCadastro
     */
    public TelaCadastro() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        nomeTextField = new javax.swing.JTextField();
        raTextField = new javax.swing.JTextField();
        emailTextField = new javax.swing.JTextField();
        cadastrarButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        senhaPasswordField = new javax.swing.JPasswordField();
        voltarButton = new javax.swing.JButton();
        telaButton = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        nomeTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nomeTextFieldActionPerformed(evt);
            }
        });
        getContentPane().add(nomeTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 180, 600, 40));

        raTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                raTextFieldActionPerformed(evt);
            }
        });
        getContentPane().add(raTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 260, 600, 40));

        emailTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailTextFieldActionPerformed(evt);
            }
        });
        getContentPane().add(emailTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 350, 600, 40));

        cadastrarButton.setBackground(new java.awt.Color(16, 31, 53));
        cadastrarButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/cadastrarButtonImage.png"))); // NOI18N
        cadastrarButton.setBorderPainted(false);
        cadastrarButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cadastrarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadastrarButtonActionPerformed(evt);
            }
        });
        getContentPane().add(cadastrarButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 550, 190, 40));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/cadastrarButtonImage.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 540, -1, -1));
        getContentPane().add(senhaPasswordField, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 450, 600, 40));

        voltarButton.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        voltarButton.setForeground(new java.awt.Color(255, 255, 255));
        voltarButton.setText("voltar");
        voltarButton.setContentAreaFilled(false);
        voltarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                voltarButtonActionPerformed(evt);
            }
        });
        getContentPane().add(voltarButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 620, -1, -1));

        telaButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/telaCadastroImage.png"))); // NOI18N
        telaButton.setText(" ");
        getContentPane().add(telaButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1280, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nomeTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nomeTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nomeTextFieldActionPerformed

    private void emailTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emailTextFieldActionPerformed

    private void cadastrarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadastrarButtonActionPerformed
        try{
            String nome = nomeTextField.getText();
            String ra = raTextField.getText();
            String email = emailTextField.getText();
            String senha = new String(senhaPasswordField.getPassword());
            var u = new Usuario(ra, nome, email, senha);
            var dao = new UsuarioDAO();
            String pontuacao = "0";
            //var r = new Respostas(ra, nome, pontuacao);
            //var rDAO = new RespostasDAO();
            //colocar aqui o código para verificar se todos os campos estão preenchidos!
            if(dao.verificacao(u)){
                 showMessageDialog(null, "Usuário já cadastrado.");
            //}else if(rDAO.verificacao(r)){
                //showMessageDialog(null, "Usuário já cadastrado.");
            } else {
                var telaLogin = new TelaLoginFuncionaAmem();
                telaLogin.setVisible(true);
                dispose();
            }
            dao.cadastrar(u); 
            //rDAO.cadastrar(r);
            
            
        }
        catch(Exception e){
             showMessageDialog(null, "Falha técnica. Tente novamente mais tarde");
             e.printStackTrace();
        }
    }//GEN-LAST:event_cadastrarButtonActionPerformed

    private void raTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_raTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_raTextFieldActionPerformed

    private void voltarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_voltarButtonActionPerformed
        var telaLogin = new TelaLoginFuncionaAmem();
        telaLogin.setVisible(true);
        dispose();
    }//GEN-LAST:event_voltarButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaCadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaCadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaCadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaCadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaCadastro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cadastrarButton;
    private javax.swing.JTextField emailTextField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField nomeTextField;
    private javax.swing.JTextField raTextField;
    private javax.swing.JPasswordField senhaPasswordField;
    private javax.swing.JLabel telaButton;
    private javax.swing.JButton voltarButton;
    // End of variables declaration//GEN-END:variables
}
