/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package UI;

/**
 *
 * @author 23.01425-3
 */
public class TelaAdministradorInicial extends javax.swing.JFrame {

    /**
     * Creates new form telaAdministradorInicial
     */
    public TelaAdministradorInicial() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        manterQuestoesButton = new javax.swing.JButton();
        manterUsuarioButton = new javax.swing.JButton();
        telaLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        manterQuestoesButton.setBackground(new java.awt.Color(0, 23, 103));
        manterQuestoesButton.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        manterQuestoesButton.setForeground(new java.awt.Color(255, 255, 255));
        manterQuestoesButton.setText("manter questões");
        manterQuestoesButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        manterQuestoesButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manterQuestoesButtonActionPerformed(evt);
            }
        });
        getContentPane().add(manterQuestoesButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 200, 210, 60));

        manterUsuarioButton.setBackground(new java.awt.Color(0, 23, 103));
        manterUsuarioButton.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        manterUsuarioButton.setForeground(new java.awt.Color(255, 255, 255));
        manterUsuarioButton.setText("manter cadastros");
        manterUsuarioButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        manterUsuarioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manterUsuarioButtonActionPerformed(evt);
            }
        });
        getContentPane().add(manterUsuarioButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 290, 210, 60));

        telaLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/telaInicialAdministradorImage.png"))); // NOI18N
        getContentPane().add(telaLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void manterQuestoesButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manterQuestoesButtonActionPerformed
        var telaAdministradorQuestoes = new TelaAdministradorQuestoes();
        telaAdministradorQuestoes.setVisible(true);
        dispose();
    }//GEN-LAST:event_manterQuestoesButtonActionPerformed

    private void manterUsuarioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manterUsuarioButtonActionPerformed
        var telaAdministradorCadastros = new TelaAdministradorCadastros();
        telaAdministradorCadastros.setVisible(true);
        dispose();
    }//GEN-LAST:event_manterUsuarioButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaAdministradorInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaAdministradorInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaAdministradorInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaAdministradorInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaAdministradorInicial().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton manterQuestoesButton;
    private javax.swing.JButton manterUsuarioButton;
    private javax.swing.JLabel telaLabel;
    // End of variables declaration//GEN-END:variables
}
