/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package UI;
import Connection_Respostas.Respostas;
import Connection_MySQL_RespostasDAO.RespostasDAO;
import Jogo.Jogo;
import java.awt.Graphics2D;
import java.awt.Image;
import java.awt.geom.AffineTransform;
import java.awt.image.BufferedImage;
import java.io.File;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;

/**
 *
 * @author 23.01425-3
 */
public class TelaPontuacao extends javax.swing.JFrame {
    
    Jogo jogo;
    String ra;


    public TelaPontuacao(){
    }
    
    public TelaPontuacao(int pontuacao) {
        initComponents();
        setLocationRelativeTo(null);
           String p = Integer.toString(pontuacao);
           pontuacaoJogadorLabel.setText(p);

    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        irRankingButton = new javax.swing.JButton();
        pontuacaoJogadorLabel = new javax.swing.JLabel();
        telaLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        irRankingButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/ramkingButton.png"))); // NOI18N
        irRankingButton.setBorderPainted(false);
        irRankingButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        irRankingButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                irRankingButtonActionPerformed(evt);
            }
        });
        getContentPane().add(irRankingButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 530, 260, 40));

        pontuacaoJogadorLabel.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        pontuacaoJogadorLabel.setForeground(new java.awt.Color(0, 0, 102));
        pontuacaoJogadorLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        pontuacaoJogadorLabel.setText(" ");
        getContentPane().add(pontuacaoJogadorLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 230, 200, 60));

        telaLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/doska appeared (2).png"))); // NOI18N
        getContentPane().add(telaLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void irRankingButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_irRankingButtonActionPerformed
        var telaRanking = new TelaRanking();
        telaRanking.setVisible(true);
        dispose();
    }//GEN-LAST:event_irRankingButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPontuacao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPontuacao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPontuacao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPontuacao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                var telaPontuacao = new TelaPontuacao();
                telaPontuacao.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton irRankingButton;
    private javax.swing.JLabel pontuacaoJogadorLabel;
    private javax.swing.JLabel telaLabel;
    // End of variables declaration//GEN-END:variables
}
