/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package UI;

import Connection_MySQL_UsuarioDAO.UsuarioDAO;
import Connection_Usuarios.Usuario;
import static javax.swing.JOptionPane.showMessageDialog;

/**
 *
 * @author 23.01425-3
 */
public class TelaLoginAdministrador extends javax.swing.JFrame {

    /**
     * Creates new form TelaLoginAdministrador
     */
    public TelaLoginAdministrador() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        loginTextField = new javax.swing.JTextField();
        logarButton = new javax.swing.JButton();
        senhaPasswordField = new javax.swing.JPasswordField();
        logarButtonLabel = new javax.swing.JLabel();
        voltar = new javax.swing.JButton();
        telaLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        loginTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginTextFieldActionPerformed(evt);
            }
        });
        getContentPane().add(loginTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 330, 460, 50));

        logarButton.setBackground(new java.awt.Color(16, 31, 53));
        logarButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/logarButtonImage.png"))); // NOI18N
        logarButton.setBorderPainted(false);
        logarButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        logarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logarButtonActionPerformed(evt);
            }
        });
        getContentPane().add(logarButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 580, 170, 50));

        senhaPasswordField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                senhaPasswordFieldActionPerformed(evt);
            }
        });
        getContentPane().add(senhaPasswordField, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 440, 470, 50));

        logarButtonLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/logarButtonImage.png"))); // NOI18N
        getContentPane().add(logarButtonLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 570, -1, -1));

        voltar.setBackground(new java.awt.Color(0, 51, 102));
        voltar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        voltar.setForeground(new java.awt.Color(255, 255, 255));
        voltar.setText("voltar");
        voltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                voltarActionPerformed(evt);
            }
        });
        getContentPane().add(voltar, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 670, -1, -1));

        telaLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/telaLoginAdministradorImage.png"))); // NOI18N
        getContentPane().add(telaLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void loginTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_loginTextFieldActionPerformed

    private void logarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logarButtonActionPerformed
        try{
            String ra = loginTextField.getText();
            String senha = new String(senhaPasswordField.getPassword());
            var u = new Usuario(ra, senha);
            var dao = new UsuarioDAO();
            //se ra começar com adm.{
            if(ra.equals("admin") && senha.equals("admin")){
                var telaAdministradorInicial = new TelaAdministradorInicial();
                telaAdministradorInicial.setVisible(true);
                dispose();
            }
            else{
                showMessageDialog(null, "Usuário/senha inválidos e/ou não autorizados");
            } 
        }
        catch(Exception e){
             showMessageDialog(null, "Falha técnica. Tente novamente mais tarde");
             e.printStackTrace();
            }
    }//GEN-LAST:event_logarButtonActionPerformed

    private void senhaPasswordFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_senhaPasswordFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_senhaPasswordFieldActionPerformed

    private void voltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_voltarActionPerformed
        var telaLoginFuncionaAmem = new TelaLoginFuncionaAmem();
        telaLoginFuncionaAmem.setVisible(true);
        dispose();
    }//GEN-LAST:event_voltarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaLoginAdministrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaLoginAdministrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaLoginAdministrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaLoginAdministrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaLoginAdministrador().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton logarButton;
    private javax.swing.JLabel logarButtonLabel;
    private javax.swing.JTextField loginTextField;
    private javax.swing.JPasswordField senhaPasswordField;
    private javax.swing.JLabel telaLabel;
    private javax.swing.JButton voltar;
    // End of variables declaration//GEN-END:variables
}
