/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package UI;
import Connection_MySQL_UsuarioDAO.UsuarioDAO;
import Connection_Usuarios.Usuario;
import Jogo.Jogo;
import static javax.swing.JOptionPane.*;

/**
 *
 * @author 23.01425-3
 */
public class TelaLoginFuncionaAmem extends javax.swing.JFrame {

    /**
     * Creates new form TelaLoginFuncionaAmem
     */
    public TelaLoginFuncionaAmem() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        loginTextField = new javax.swing.JTextField();
        jogarButton = new javax.swing.JButton();
        cadastrarButton = new javax.swing.JButton();
        areaAdminButton = new javax.swing.JButton();
        senhaPasswordField = new javax.swing.JPasswordField();
        JogarButtonLabel = new javax.swing.JLabel();
        telaLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        loginTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginTextFieldActionPerformed(evt);
            }
        });
        getContentPane().add(loginTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 330, 470, 50));

        jogarButton.setBackground(new java.awt.Color(16, 31, 53));
        jogarButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/jogarButtonImage.png"))); // NOI18N
        jogarButton.setBorderPainted(false);
        jogarButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jogarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jogarButtonActionPerformed(evt);
            }
        });
        getContentPane().add(jogarButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 570, 200, 50));

        cadastrarButton.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        cadastrarButton.setForeground(new java.awt.Color(16, 31, 53));
        cadastrarButton.setText("cadastrar");
        cadastrarButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cadastrarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadastrarButtonActionPerformed(evt);
            }
        });
        getContentPane().add(cadastrarButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 640, 90, -1));

        areaAdminButton.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        areaAdminButton.setText("área do administrador");
        areaAdminButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        areaAdminButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                areaAdminButtonActionPerformed(evt);
            }
        });
        getContentPane().add(areaAdminButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 680, 160, -1));

        senhaPasswordField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                senhaPasswordFieldActionPerformed(evt);
            }
        });
        getContentPane().add(senhaPasswordField, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 440, 470, 50));

        JogarButtonLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/jogarButtonImage.png"))); // NOI18N
        getContentPane().add(JogarButtonLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 560, -1, -1));

        telaLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/telaLoginImagem.png"))); // NOI18N
        telaLabel.setText("jLabel1");
        getContentPane().add(telaLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1280, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void loginTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_loginTextFieldActionPerformed

    private void jogarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jogarButtonActionPerformed
        try{
            String ra = loginTextField.getText();
            String senha = new String(senhaPasswordField.getPassword());
            var u = new Usuario(ra, senha);
            var dao = new UsuarioDAO();
            if (dao.existe(u)){
                var telaregras1 = new TelaRegras1(ra);
                
                telaregras1.setVisible(true);
                dispose();
                
                var jogo = new Jogo();
                jogo.setRa(ra);
            }
            else{
                showMessageDialog(null, "Usuário/senha inválido");
            }
            
        }
        catch(Exception e){
             showMessageDialog(null, "Falha técnica. Tente novamente mais tarde");
             e.printStackTrace();
            }
    }//GEN-LAST:event_jogarButtonActionPerformed

    private void cadastrarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadastrarButtonActionPerformed
        var telaCadastro = new TelaCadastro();
        telaCadastro.setVisible(true);
        dispose();
    }//GEN-LAST:event_cadastrarButtonActionPerformed

    private void areaAdminButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_areaAdminButtonActionPerformed
        var telaLoginAdministrador = new TelaLoginAdministrador();
        telaLoginAdministrador.setVisible(true);
        dispose();
    }//GEN-LAST:event_areaAdminButtonActionPerformed

    private void senhaPasswordFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_senhaPasswordFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_senhaPasswordFieldActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaLoginFuncionaAmem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaLoginFuncionaAmem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaLoginFuncionaAmem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaLoginFuncionaAmem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaLoginFuncionaAmem().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel JogarButtonLabel;
    private javax.swing.JButton areaAdminButton;
    private javax.swing.JButton cadastrarButton;
    private javax.swing.JButton jogarButton;
    private javax.swing.JTextField loginTextField;
    private javax.swing.JPasswordField senhaPasswordField;
    private javax.swing.JLabel telaLabel;
    // End of variables declaration//GEN-END:variables
}
