/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package UI;

import Connection_MySQL_QuestoesDAO.QuestoesDAO;
import Connection_Questoes.Questoes;
import static javax.swing.JOptionPane.showMessageDialog;

/**
 *
 * @author Douglas
 */
public class TelaAdministradorAtuQuest extends javax.swing.JFrame {

    /**
     * Creates new form TelaAdministradorAtuQuest
     */
    public TelaAdministradorAtuQuest() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        atualizarButton = new javax.swing.JButton();
        novoEnunciadoTextField = new javax.swing.JTextField();
        novoIdTextField = new javax.swing.JTextField();
        novaAlternativaATextField = new javax.swing.JTextField();
        novaAlternativaBTextField = new javax.swing.JTextField();
        novaAlternativaCTextField = new javax.swing.JTextField();
        novaAlternativaDTextField = new javax.swing.JTextField();
        novaAltCorretaLabel = new javax.swing.JLabel();
        novaAltCorretaA = new javax.swing.JRadioButton();
        novaAltCorretaB = new javax.swing.JRadioButton();
        novaAltCorretaC = new javax.swing.JRadioButton();
        novaAltCorretaD = new javax.swing.JRadioButton();
        idBuscaTextField = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        atualizarButton.setText("atualizar");
        atualizarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                atualizarButtonActionPerformed(evt);
            }
        });

        novoEnunciadoTextField.setBorder(javax.swing.BorderFactory.createTitledBorder("novo enunciado da questão"));
        novoEnunciadoTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                novoEnunciadoTextFieldActionPerformed(evt);
            }
        });

        novoIdTextField.setBorder(javax.swing.BorderFactory.createTitledBorder("novo id da questão"));
        novoIdTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                novoIdTextFieldActionPerformed(evt);
            }
        });

        novaAlternativaATextField.setBorder(javax.swing.BorderFactory.createTitledBorder("nova alternativa A"));
        novaAlternativaATextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                novaAlternativaATextFieldActionPerformed(evt);
            }
        });

        novaAlternativaBTextField.setBorder(javax.swing.BorderFactory.createTitledBorder("nova alternativa B"));
        novaAlternativaBTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                novaAlternativaBTextFieldActionPerformed(evt);
            }
        });

        novaAlternativaCTextField.setBorder(javax.swing.BorderFactory.createTitledBorder("nova alternativa C"));
        novaAlternativaCTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                novaAlternativaCTextFieldActionPerformed(evt);
            }
        });

        novaAlternativaDTextField.setBorder(javax.swing.BorderFactory.createTitledBorder("nova Alternativa D"));
        novaAlternativaDTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                novaAlternativaDTextFieldActionPerformed(evt);
            }
        });

        novaAltCorretaLabel.setText("Nova alternativa correta:");

        buttonGroup1.add(novaAltCorretaA);
        novaAltCorretaA.setText("Alternativa A");

        buttonGroup1.add(novaAltCorretaB);
        novaAltCorretaB.setText("Alternativa B");

        buttonGroup1.add(novaAltCorretaC);
        novaAltCorretaC.setText("Alternativa C");

        buttonGroup1.add(novaAltCorretaD);
        novaAltCorretaD.setText("Alternativa D");

        idBuscaTextField.setActionCommand("<Not Set>");
        idBuscaTextField.setBorder(javax.swing.BorderFactory.createTitledBorder("id da questão a ser atualizada"));
        idBuscaTextField.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(386, 386, 386)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(novaAlternativaATextField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 441, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(novaAlternativaBTextField)
                            .addComponent(novaAlternativaCTextField)
                            .addComponent(novaAlternativaDTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 441, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(novaAltCorretaA)
                            .addComponent(novaAltCorretaLabel)
                            .addComponent(novaAltCorretaB))
                        .addGap(135, 135, 135)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(novaAltCorretaC)
                            .addComponent(novaAltCorretaD))))
                .addContainerGap(290, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(novoIdTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 331, Short.MAX_VALUE)
                    .addComponent(novoEnunciadoTextField)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(80, 80, 80)
                        .addComponent(atualizarButton, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(idBuscaTextField))
                .addGap(351, 351, 351))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(idBuscaTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(novoEnunciadoTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(novoIdTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(novaAlternativaATextField, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(17, 17, 17)
                .addComponent(novaAlternativaBTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(novaAlternativaCTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(novaAlternativaDTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23)
                .addComponent(novaAltCorretaLabel)
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(novaAltCorretaA)
                    .addComponent(novaAltCorretaC))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(novaAltCorretaB)
                    .addComponent(novaAltCorretaD))
                .addGap(31, 31, 31)
                .addComponent(atualizarButton, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void novoEnunciadoTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_novoEnunciadoTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_novoEnunciadoTextFieldActionPerformed

    private void novaAlternativaATextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_novaAlternativaATextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_novaAlternativaATextFieldActionPerformed

    private void novaAlternativaCTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_novaAlternativaCTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_novaAlternativaCTextFieldActionPerformed

    private void novoIdTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_novoIdTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_novoIdTextFieldActionPerformed

    private void novaAlternativaBTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_novaAlternativaBTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_novaAlternativaBTextFieldActionPerformed

    private void novaAlternativaDTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_novaAlternativaDTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_novaAlternativaDTextFieldActionPerformed

    private void atualizarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_atualizarButtonActionPerformed
        try{
            String idBusca1 = idBuscaTextField.getText();
            String novoEnunciado = novoEnunciadoTextField.getText();
            String novoId = novoIdTextField.getText();
            String novaAlternativaA = novaAlternativaATextField.getText();
            String novaAlternativaB = novaAlternativaBTextField.getText();
            String novaAlternativaC = novaAlternativaCTextField.getText();
            String novaAlternativaD = novaAlternativaDTextField.getText();
            
            String respostas = null;
                if(novaAltCorretaA.isSelected()){
                    respostas = novaAltCorretaA.getText();
                }
                if(novaAltCorretaB.isSelected()){
                    respostas = novaAltCorretaB.getText();
                }
                if(novaAltCorretaC.isSelected()){
                    respostas = novaAltCorretaC.getText();
                }
                if(novaAltCorretaD.isSelected()){
                    respostas = novaAltCorretaD.getText();
                }
            
            Questoes q = new Questoes(novoId, novaAlternativaA, novaAlternativaB, novaAlternativaC, novaAlternativaD, novoEnunciado, respostas, idBusca1);
            QuestoesDAO dao = new QuestoesDAO();
            if(dao.verificacao(q)){
            }
            else{
                var administradorQuestoes = new TelaAdministradorQuestoes();
                administradorQuestoes.setVisible(true);
                dispose();
            }
            dao.atualizar(q);


        }
        catch(Exception e){
             showMessageDialog(null, "Falha técnica. Tente novamente mais tarde");
             e.printStackTrace();
        }
    }//GEN-LAST:event_atualizarButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaAdministradorAtuQuest.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaAdministradorAtuQuest.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaAdministradorAtuQuest.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaAdministradorAtuQuest.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */ 
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaAdministradorAtuQuest().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton atualizarButton;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JTextField idBuscaTextField;
    private javax.swing.JRadioButton novaAltCorretaA;
    private javax.swing.JRadioButton novaAltCorretaB;
    private javax.swing.JRadioButton novaAltCorretaC;
    private javax.swing.JRadioButton novaAltCorretaD;
    private javax.swing.JLabel novaAltCorretaLabel;
    private javax.swing.JTextField novaAlternativaATextField;
    private javax.swing.JTextField novaAlternativaBTextField;
    private javax.swing.JTextField novaAlternativaCTextField;
    private javax.swing.JTextField novaAlternativaDTextField;
    private javax.swing.JTextField novoEnunciadoTextField;
    private javax.swing.JTextField novoIdTextField;
    // End of variables declaration//GEN-END:variables
}
